table _Intervals
	lineageTag: 2d0d1f70-0797-401f-89f1-4c130edd27bf

	column Interval
		dataType: string
		lineageTag: a3dc2397-b50a-46ba-af74-66a3a210abc4
		summarizeBy: none
		sourceColumn: Interval
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: ea3db72e-da64-4f53-a185-63bbc7b0e15e
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition _Intervals = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcknMzKlU0lEyVIrViVYKT03NBnONwFzf/LySDDDfGMwPLE0sKkktAouYgEUiUxMhXFOl2FgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Interval = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Interval", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

